### ISSUE TITLE
User-configurable time and level

### ISSUE THREAD

**Issue by ernesto-jimenez** [goadesign/clue#72]
It might be good to allow configurations to:
1. Disable `time` or tweak the format
2. Change the name of the field for severity or disable it entirely. e.g.: Google Cloud Logging expects a `severity` rather than a `level` field.

**Comment by raphael** [comment]
Both of these are already possible via custom formatters, a bit on the fence as to whether it's worth adding options on top? Also, the time information is important to enable the buffering feature (the time the log entry is created is not necessarily the same as the time the log entry is written) so I'm not sure there should be a mechanism to disable it and let people shoot themselves in the foot - could be convinced otherwise though.
